Repository cgerard321/champlain_petclinic, pull requests merged in 2023-09, with the labels that each got.

#374 doc(VIST-CPC-795): updated readme with the requirements needed for a user story to be considered done
  README.md
Labels: documentation

#371 conf(VIST-CPC-769): edit files to disable non reactive version of visits service
  api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClient.java
  api-gateway/src/main/resources/application.yml
  api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClientIntegrationTest.java
  docker-compose.yml
  settings.gradle
  visits-service-new/build.gradle
  visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitServiceImpl.java
  visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitController.java
  visits-service-new/src/main/resources/application.yml
Labels: CONF, VIST

#419 Feat/invt cpc 741 search products by fields good pt1
  api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/InventoryServiceClient.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Inventory/InventoryResponseDTO.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java
  api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/InventoryServiceClientIntegrationTest.java
  api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java
  inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryService.java
  inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceImpl.java
  inventory-service/src/main/java/com/petclinic/inventoryservice/datalayer/Product/ProductRepository.java
  inventory-service/src/main/java/com/petclinic/inventoryservice/presentationlayer/InventoryController.java
  inventory-service/src/test/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceUnitTest.java
  inventory-service/src/test/java/com/petclinic/inventoryservice/datalayer/Product/ProductRepositoryTest.java
  inventory-service/src/test/java/com/petclinic/inventoryservice/presentationlayer/InventoryControllerIntegrationTest.java
  inventory-service/src/test/java/com/petclinic/inventoryservice/presentationlayer/InventoryControllerUnitTest.java
Labels: INVT

#427 feat(INVT-CPC-734): Update product inside of inventory
  api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/InventoryServiceClient.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java
  api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java
  inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryService.java
  inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceImpl.java
  inventory-service/src/main/java/com/petclinic/inventoryservice/datalayer/Product/ProductRepository.java
  inventory-service/src/main/java/com/petclinic/inventoryservice/presentationlayer/InventoryController.java
  inventory-service/src/test/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceUnitTest.java
  inventory-service/src/test/java/com/petclinic/inventoryservice/datalayer/Product/ProductRepositoryTest.java
  inventory-service/src/test/java/com/petclinic/inventoryservice/presentationlayer/InventoryControllerIntegrationTest.java
  inventory-service/src/test/java/com/petclinic/inventoryservice/presentationlayer/InventoryControllerUnitTest.java
Labels: INVT

#447 Feat/(INVT-CPC-730): ability to add a product to an inventory pt2
  api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java
  api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/InventoryServiceClientIntegrationTest.java
  api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java
  inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceImpl.java
  inventory-service/src/test/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceUnitTest.java
  inventory-service/src/test/java/com/petclinic/inventoryservice/presentationlayer/InventoryControllerIntegrationTest.java
  inventory-service/src/test/java/com/petclinic/inventoryservice/presentationlayer/InventoryControllerUnitTest.java
Labels: INVT

#450 (INVT-CPC-730): ability to add product in inventory pt3
  api-gateway/src/main/resources/static/index.html
  api-gateway/src/main/resources/static/scripts/inventory-list/inventory-service.js
  api-gateway/src/main/resources/static/scripts/inventory-product-list/inventory-product-list.controller.js
  api-gateway/src/main/resources/static/scripts/inventory-product-list/inventory-product-list.template.html
  api-gateway/src/main/resources/static/scripts/product-form/product-form.controller.js
  api-gateway/src/main/resources/static/scripts/product-form/product-form.js
  api-gateway/src/main/resources/static/scripts/product-form/product-form.template.html
Labels: INVT

#461 feat(AUTH-CPC-742): create account
  api-gateway/src/main/java/com/petclinic/bffapigateway/config/GlobalServletExceptionHandler.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/AuthServiceClient.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java
  api-gateway/src/main/resources/static/scripts/auth/signup/signup-form.controller.js
  api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java
  auth-service/src/main/java/com/auth/authservice/Util/AdminAccount/DatabaseLoaderService.java
  auth-service/src/main/java/com/auth/authservice/Util/Configuration/Security/CustomBasicAuthenticationEntryPoint.java
  auth-service/src/main/java/com/auth/authservice/Util/Configuration/Security/PasswordStrengthCheck.java
  auth-service/src/main/java/com/auth/authservice/Util/Configuration/Security/PasswordValidation.java
  auth-service/src/main/java/com/auth/authservice/Util/Configuration/Security/SecurityConfig.java
  auth-service/src/main/java/com/auth/authservice/Util/GlobalControllerExceptionHandlerConfig.java
  auth-service/src/main/java/com/auth/authservice/businesslayer/UserService.java
  auth-service/src/main/java/com/auth/authservice/businesslayer/UserServiceImpl.java
  auth-service/src/main/java/com/auth/authservice/datalayer/user/User.java
  auth-service/src/main/java/com/auth/authservice/datalayer/user/UserRepo.java
  auth-service/src/main/java/com/auth/authservice/domainclientlayer/Mail/MailServiceImpl.java
  auth-service/src/main/java/com/auth/authservice/presentationlayer/User/UserController.java
  auth-service/src/main/java/com/auth/authservice/presentationlayer/User/UserIDLessRoleLessDTO.java
  auth-service/src/main/java/com/auth/authservice/security/JwtTokenFilter.java
  auth-service/src/main/resources/application.yml
  auth-service/src/test/java/com/auth/authservice/businesslayer/AuthServiceUserServiceTests.java
  auth-service/src/test/java/com/auth/authservice/presentationlayer/User/UserControllerIntegrationTest.java
Labels: AUTH

#470 feat(VETS-CPC-938): get all educations of a vet
  api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClient.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Vets/EducationRequestDTO.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Vets/EducationResponseDTO.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java
  api-gateway/src/main/resources/static/scripts/vet-details/vet-details.controller.js
  api-gateway/src/main/resources/static/scripts/vet-details/vet-details.template.html
  api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClientIntegrationTest.java
  api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java
  vet-service/src/main/java/com/petclinic/vet/dataaccesslayer/Education.java
  vet-service/src/main/java/com/petclinic/vet/dataaccesslayer/EducationRepository.java
  vet-service/src/main/java/com/petclinic/vet/presentationlayer/VetController.java
  vet-service/src/main/java/com/petclinic/vet/servicelayer/DataSetupService.java
  vet-service/src/main/java/com/petclinic/vet/servicelayer/EducationRequestDTO.java
  vet-service/src/main/java/com/petclinic/vet/servicelayer/EducationResponseDTO.java
  vet-service/src/main/java/com/petclinic/vet/servicelayer/EducationService.java
  vet-service/src/main/java/com/petclinic/vet/servicelayer/EducationServiceImpl.java
  vet-service/src/main/java/com/petclinic/vet/util/EntityDtoUtil.java
  vet-service/src/test/java/com/petclinic/vet/dataaccesslayer/EducationRepositoryTest.java
  vet-service/src/test/java/com/petclinic/vet/presentationlayer/VetControllerIntegrationTest.java
  vet-service/src/test/java/com/petclinic/vet/presentationlayer/VetControllerUnitTest.java
  vet-service/src/test/java/com/petclinic/vet/servicelayer/EducationServiceImplTest.java
Labels: VETS

#469 feat(VIST-CPC-748): full story exception handling fix front end
  api-gateway/src/main/java/com/petclinic/bffapigateway/config/GlobalExceptionHandler.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/config/GlobalServletExceptionHandler.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClient.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Visits/VisitRequestDTO.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/exceptions/BadRequestException.java
  api-gateway/src/main/resources/static/scripts/visits/visits.controller.js
  api-gateway/src/main/resources/static/scripts/visits/visits.template.html
  api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClientIntegrationTest.java
  visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitServiceImpl.java
  visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/Exceptions/BadRequestException.java
  visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/Exceptions/GlobalControllerExceptionHandler.java
  visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitServiceImplTest.java
  visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/Exceptions/BadRequestExceptionTest.java
  visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/Exceptions/GlobalControllerExceptionHandlerTest.java
  visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitsControllerIntegrationTest.java
Labels: VIST

#474 feat(VIST-CPC-949): updated datetime formatter
  api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Visits/VisitDetails.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Visits/VisitRequestDTO.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Visits/VisitResponseDTO.java
  api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClientIntegrationTest.java
  api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java
  visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitService.java
  visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/DataLayer/DataSetupService.java
  visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/DataLayer/Visit.java
  visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitRequestDTO.java
  visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitResponseDTO.java
  visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitServiceImplTest.java
  visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/DataLayer/VisitRepoTest.java
  visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitControllerUnitTest.java
  visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitsControllerIntegrationTest.java
Labels: VIST

#482 bug(INVT-CPC-872): implement exceptions in domain_client
  api-gateway/src/main/java/com/petclinic/bffapigateway/config/GlobalExceptionHandler.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/InventoryServiceClient.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/exceptions/InvalidInputsInventoryException.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/exceptions/InventoryNotFoundException.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/exceptions/ProductListNotFoundException.java
  api-gateway/src/main/resources/static/scripts/inventory-product-list/inventory-product-list.controller.js
  api-gateway/src/main/resources/static/scripts/product-form/product-form.controller.js
  inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceImpl.java
  inventory-service/src/main/java/com/petclinic/inventoryservice/utils/DataBaseLoaderService.java
  inventory-service/src/test/java/com/petclinic/inventoryservice/presentationlayer/InventoryControllerIntegrationTest.java
Labels: INVT

#473 feat(AUTH-CPC-952):Create user specific endpoints
  api-gateway/src/main/java/com/petclinic/bffapigateway/config/GlobalExceptionHandler.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/config/GlobalServletExceptionHandler.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/AuthServiceClient.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/CustomersServiceClient.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Auth/Register.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Auth/Role.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/CustomerDTOs/OwnerRequestDTO.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/CustomerDTOs/OwnerResponseDTO.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/exceptions/ForbiddenAccessException.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/utils/Security/Annotations/IsUserSpecific.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/utils/Security/Annotations/PasswordStrengthCheck.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/utils/Security/Annotations/PasswordValidation.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/utils/Security/Filters/IsUserFilter.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/utils/Security/Filters/JwtTokenFilter.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/utils/Security/Filters/JwtTokenUtil.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/utils/Security/Filters/RoleFilter.java
  api-gateway/src/main/resources/static/index.html
  api-gateway/src/main/resources/static/scripts/app.js
  api-gateway/src/main/resources/static/scripts/auth/signup/signup-form.controller.js
  api-gateway/src/main/resources/static/scripts/auth/signup/signup-form.template.html
  api-gateway/src/main/resources/static/scripts/fragments/nav.html
  api-gateway/src/main/resources/static/scripts/owner-details/owner-details.js
  api-gateway/src/main/resources/static/scripts/owner-register/owner-register.controller.js
  api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/AuthServiceClientIntegrationTest.java
  api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/CustomerServiceClientIntegrationTest.java
  api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java
  api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayControllerFilterIntegrationTest.java
  auth-service/build.gradle
  auth-service/src/main/java/com/auth/authservice/Util/AdminAccount/DatabaseLoaderService.java
  auth-service/src/main/java/com/auth/authservice/Util/Configuration/Security/SecurityConfig.java
  auth-service/src/main/java/com/auth/authservice/businesslayer/UserServiceImpl.java
  auth-service/src/main/java/com/auth/authservice/datalayer/user/User.java
  auth-service/src/main/java/com/auth/authservice/datalayer/user/UserIdentifier.java
  auth-service/src/main/java/com/auth/authservice/presentationlayer/User/UserController.java
  auth-service/src/main/java/com/auth/authservice/presentationlayer/User/UserIDLessRoleLessDTO.java
  auth-service/src/main/java/com/auth/authservice/security/SecurityConst.java
  auth-service/src/test/java/com/auth/authservice/presentationlayer/User/UserControllerIntegrationTest.java
  customers-service-reactive/src/main/java/com/petclinic/customersservice/business/OwnerServiceImpl.java
  customers-service-reactive/src/main/java/com/petclinic/customersservice/data/Owner.java
  customers-service-reactive/src/main/java/com/petclinic/customersservice/presentationlayer/OwnerController.java
Labels: AUTH

#481 conf(INVT-CPC-874): invt bring up to date project dependencies
  inventory-service/Dockerfile
  inventory-service/build.gradle
  inventory-service/gradle/wrapper/gradle-wrapper.properties
  inventory-service/src/main/resources/application.yml
Labels: INVT
