Repository cgerard321/champlain_petclinic, pull requests merged in 2023-10, with the labels that each got.

#476 conf(VIST-CPC-958): adding qodana to cicd pipeline
  .github/workflows/gradle.yml
  .github/workflows/qodana_code_quality.yml
  qodana.yaml
  visits-service-new/build.gradle
Labels: CONF, VIST

#500 feat(INVT-CPC-862): apig return proper on delete and post and update tests in api gateway
  api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClient.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java
  api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java
Labels: VETS, AUTH, BILL, APIG, VIST, INVT

#502 feat(VETS-CPC 836): getting the top 3 vets based on the highest ratings average
  api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClient.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Vets/VetAverageRatingDTO.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java
  api-gateway/src/main/resources/static/scripts/vet-list/vet-list.controller.js
  api-gateway/src/main/resources/static/scripts/vet-list/vet-list.template.html
  api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClientIntegrationTest.java
  api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java
  vet-service/src/main/java/com/petclinic/vet/dataaccesslayer/education/Education.java
  vet-service/src/main/java/com/petclinic/vet/dataaccesslayer/education/EducationRepository.java
  vet-service/src/main/java/com/petclinic/vet/dataaccesslayer/ratings/PredefinedDescription.java
  vet-service/src/main/java/com/petclinic/vet/dataaccesslayer/ratings/Rating.java
  vet-service/src/main/java/com/petclinic/vet/dataaccesslayer/ratings/RatingRepository.java
  vet-service/src/main/java/com/petclinic/vet/presentationlayer/VetController.java
  vet-service/src/main/java/com/petclinic/vet/servicelayer/DataSetupService.java
  vet-service/src/main/java/com/petclinic/vet/servicelayer/VetAverageRatingDTO.java
  vet-service/src/main/java/com/petclinic/vet/servicelayer/education/EducationRequestDTO.java
  vet-service/src/main/java/com/petclinic/vet/servicelayer/education/EducationResponseDTO.java
  vet-service/src/main/java/com/petclinic/vet/servicelayer/education/EducationService.java
  vet-service/src/main/java/com/petclinic/vet/servicelayer/education/EducationServiceImpl.java
  vet-service/src/main/java/com/petclinic/vet/servicelayer/ratings/RatingRequestDTO.java
  vet-service/src/main/java/com/petclinic/vet/servicelayer/ratings/RatingResponseDTO.java
  vet-service/src/main/java/com/petclinic/vet/servicelayer/ratings/RatingService.java
  vet-service/src/main/java/com/petclinic/vet/servicelayer/ratings/RatingServiceImpl.java
  vet-service/src/main/java/com/petclinic/vet/util/EntityDtoUtil.java
  vet-service/src/test/java/com/petclinic/vet/dataaccesslayer/EducationRepositoryTest.java
  vet-service/src/test/java/com/petclinic/vet/dataaccesslayer/RatingRepositoryTest.java
  vet-service/src/test/java/com/petclinic/vet/presentationlayer/VetControllerIntegrationTest.java
  vet-service/src/test/java/com/petclinic/vet/presentationlayer/VetControllerUnitTest.java
  vet-service/src/test/java/com/petclinic/vet/servicelayer/EducationServiceImplTest.java
  vet-service/src/test/java/com/petclinic/vet/servicelayer/RatingServiceImplTest.java
Labels: VETS

#492 feat(VIST-CPC-929): added search fields to the visits table list
  api-gateway/src/main/resources/static/scripts/visit-list/visit-list.template.html
Labels: feat, VIST

#511 feat(VIST-CPC-947): implement delete all canceled visits functionality
  api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClient.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Visits/Status.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java
  api-gateway/src/main/resources/static/scripts/visit-list/visit-list.controller.js
  api-gateway/src/main/resources/static/scripts/visit-list/visit-list.js
  api-gateway/src/main/resources/static/scripts/visit-list/visit-list.template.html
  api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClientIntegrationTest.java
  api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java
  visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitService.java
  visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitServiceImpl.java
  visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/DataLayer/DataSetupService.java
  visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/DataLayer/Status.java
  visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitController.java
  visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitServiceImplTest.java
  visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitControllerUnitTest.java
  visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitsControllerIntegrationTest.java
Labels: feat, VIST

#478 bug(VIST-CPC 930): fixing bug related to date not being displayed on a new visit
  api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Visits/VisitRequestDTO.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java
  api-gateway/src/main/resources/static/scripts/visit-list/visit-list.template.html
  api-gateway/src/main/resources/static/scripts/visits/visits.component.js
  api-gateway/src/main/resources/static/scripts/visits/visits.controller.js
  api-gateway/src/main/resources/static/scripts/visits/visits.template.html
  api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClientIntegrationTest.java
  api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java
Labels: bug, VIST

#536 feat(VIST-CPC-913): sorting visits into status tables
  api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClient.java
  api-gateway/src/main/resources/static/scripts/visit-list/visit-list.controller.js
  api-gateway/src/main/resources/static/scripts/visit-list/visit-list.template.html
  api-gateway/src/main/resources/static/scripts/visits/visits.controller.js
Labels: VIST

#552 feat(VIST-CPC-1001): back button added to newVisit form
  api-gateway/src/main/resources/static/scripts/visits/visits.controller.js
  api-gateway/src/main/resources/static/scripts/visits/visits.template.html
Labels: feat, VIST

#554 feat(VIST-CPC-946) add option to choose owner and pet for visit
  api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Visits/VisitRequestDTO.java
  api-gateway/src/main/resources/static/scripts/visits/visits.controller.js
  api-gateway/src/main/resources/static/scripts/visits/visits.template.html
Labels: feat, VIST

#553 feat: (INVT-CPC-873) add pagination functionality to inventory product list
  api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/InventoryServiceClient.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java
  api-gateway/src/main/resources/static/scripts/inventory-list/inventory-list.controller.js
  api-gateway/src/main/resources/static/scripts/inventory-product-list/inventory-product-list.controller.js
  api-gateway/src/main/resources/static/scripts/inventory-product-list/inventory-product-list.js
  api-gateway/src/main/resources/static/scripts/inventory-product-list/inventory-product-list.template.html
  api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/InventoryServiceClientIntegrationTest.java
  api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java
  inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryService.java
  inventory-service/src/main/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceImpl.java
  inventory-service/src/main/java/com/petclinic/inventoryservice/datalayer/Product/ProductRepository.java
  inventory-service/src/main/java/com/petclinic/inventoryservice/presentationlayer/InventoryController.java
  inventory-service/src/main/java/com/petclinic/inventoryservice/utils/DataBaseLoaderService.java
  inventory-service/src/test/java/com/petclinic/inventoryservice/businesslayer/ProductInventoryServiceUnitTest.java
  inventory-service/src/test/java/com/petclinic/inventoryservice/presentationlayer/InventoryControllerIntegrationTest.java
Labels: INVT

#555 conf(INVT-CPC-877): Closed the opened ports to the services in the docker-compose
  docker-compose.yml
Labels: CONF

#563 feat(VIST-CPC-1005): ensure no duplicate visit time
  api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClient.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/exceptions/DuplicateTimeException.java
  api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClientIntegrationTest.java
  visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitServiceImpl.java
  visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/DataLayer/VisitRepo.java
  visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/Exceptions/DuplicateTimeException.java
  visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/Exceptions/GlobalControllerExceptionHandler.java
  visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitServiceImplTest.java
  visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/Exceptions/GlobalControllerExceptionHandlerTest.java
  visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitsControllerIntegrationTest.java
Labels: feat, VIST

#579 feat(VIST-CPC-927): implementing aggregation and details page
  api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Visits/VisitResponseDTO.java
  api-gateway/src/main/resources/static/index.html
  api-gateway/src/main/resources/static/scripts/app.js
  api-gateway/src/main/resources/static/scripts/visit-details-info/visit.component.js
  api-gateway/src/main/resources/static/scripts/visit-details-info/visit.controller.js
  api-gateway/src/main/resources/static/scripts/visit-details-info/visit.details.template.html
  api-gateway/src/main/resources/static/scripts/visit-details-info/visit.js
  api-gateway/src/main/resources/static/scripts/visit-list/visit-list.template.html
  api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClientIntegrationTest.java
  api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java
  visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitServiceImpl.java
  visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/DataLayer/DataSetupService.java
  visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitResponseDTO.java
  visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/Utils/EntityDtoUtil.java
  visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/VisitsServiceNewApplication.java
  visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitServiceImplTest.java
  visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/DomainClientLayer/PetsClientUnitTest.java
  visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/DomainClientLayer/VetsClientUnitTest.java
  visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/PresentationLayer/VisitsControllerIntegrationTest.java
  visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/Utils/EntityDtoUtilTest.java
Labels: feat, VIST

#576 Feat(AUTH-CPC-740): User Can Logout
  api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/AuthServiceClient.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java
  api-gateway/src/main/resources/static/scripts/fragments/nav.html
  api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/AuthServiceClientIntegrationTest.java
  api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java
Labels: feat, AUTH

#586 bug(VIST-CPC-817): add missing tests for entityDtoUtil and visitsServiceClient
  api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClientIntegrationTest.java
  visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitServiceImplTest.java
  visits-service-new/src/test/java/com/petclinic/visits/visitsservicenew/Utils/EntityDtoUtilTest.java
Labels: bug, VIST

#573 feat(AUTH-CPC-755): Add More Roles Front End
  api-gateway/src/main/resources/static/index.html
  api-gateway/src/main/resources/static/scripts/app.js
  api-gateway/src/main/resources/static/scripts/auth/admin-panel/admin-panel.template.html
  api-gateway/src/main/resources/static/scripts/auth/update-role-form/role-update.component.js
  api-gateway/src/main/resources/static/scripts/auth/update-role-form/role-update.config.js
  api-gateway/src/main/resources/static/scripts/auth/update-role-form/role-update.controller.js
  api-gateway/src/main/resources/static/scripts/auth/update-role-form/role-update.service.js
  api-gateway/src/main/resources/static/scripts/auth/update-role-form/role-update.template.html
  auth-service/src/main/java/com/petclinic/authservice/businesslayer/UserService.java
  auth-service/src/main/java/com/petclinic/authservice/datalayer/user/UserRepo.java
  auth-service/src/main/java/com/petclinic/authservice/presentationlayer/User/RolesChangeRequestDTO.java
  auth-service/src/test/java/com/petclinic/authservice/presentationlayer/User/UserControllerIntegrationTest.java
Labels: feat, AUTH

#590 bug(VIST-CPC-1015): add more coverage to api-gateway tests
  api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VisitsServiceClientIntegrationTest.java
  api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java
  visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitServiceImpl.java
Labels: bug, VIST
