Repository cgerard321/champlain_petclinic, pull requests merged in 2025-09, with the labels that each got.

#1063 bug(CUST-CPC-1438): Fix Customer Api Calls
  api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/AuthServiceClient.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/CustomersServiceClient.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/OwnerController.java
  petclinic-frontend/src/features/customers/api/addOwner.ts
  petclinic-frontend/src/features/customers/api/addPet.ts
  petclinic-frontend/src/features/customers/api/deleteOwner.ts
  petclinic-frontend/src/features/customers/api/deletePet.ts
  petclinic-frontend/src/features/customers/api/getAllOwners.ts
  petclinic-frontend/src/features/customers/api/getOwner.ts
  petclinic-frontend/src/features/customers/api/getPet.ts
  petclinic-frontend/src/features/customers/api/updateOwner.ts
  petclinic-frontend/src/features/customers/api/updatePet.ts
  petclinic-frontend/src/features/customers/components/AdminUpdateCustomerForm.tsx
  petclinic-frontend/src/features/customers/components/CustomerDetails.tsx
  petclinic-frontend/src/features/customers/components/UpdateCustomerForm.tsx
  petclinic-frontend/src/features/customers/components/UpdatePetForm.tsx
  petclinic-frontend/src/pages/Customer/AllOwners.tsx
  petclinic-frontend/src/pages/Customer/ProfilePage.tsx
Labels: bug, CUST

#1081 feat(BILL-CPC-1464): improve bill PDF layout with professional receipt formatting
  billing-service/src/main/java/com/petclinic/billing/util/PdfGenerator.java
Labels: feat, BILL

#1097 but(VIST-1397): fix api calls in vist
  api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java
  petclinic-frontend/src/features/visits/Emergency/Api/addEmergency.ts
  petclinic-frontend/src/features/visits/Emergency/Api/deleteEmergency.ts
  petclinic-frontend/src/features/visits/Emergency/Api/getAllEmergency.ts
  petclinic-frontend/src/features/visits/Emergency/Api/getEmergencyById.ts
  petclinic-frontend/src/features/visits/Emergency/Api/getEmergencyVisits.ts
  petclinic-frontend/src/features/visits/Emergency/Api/getEmergencyVisitsByOwnerId.ts
  petclinic-frontend/src/features/visits/Emergency/Api/updateEmegency.ts
  petclinic-frontend/src/features/visits/EmergencyVisitCustomer.tsx
  petclinic-frontend/src/features/visits/Review/Api/addCustomerReview.ts
  petclinic-frontend/src/features/visits/Review/Api/addReview.ts
  petclinic-frontend/src/features/visits/Review/Api/deleteReview.ts
  petclinic-frontend/src/features/visits/Review/Api/editReview.ts
  petclinic-frontend/src/features/visits/Review/Api/getAllCustomerReviews.ts
  petclinic-frontend/src/features/visits/Review/Api/getAllReviews.ts
  petclinic-frontend/src/features/visits/Review/Api/getReview.ts
  petclinic-frontend/src/features/visits/Review/Api/getVisitByVisitId.ts
  petclinic-frontend/src/features/visits/Review/CustomerReviewsList.tsx
  petclinic-frontend/src/features/visits/Review/EditReviewForm.tsx
  petclinic-frontend/src/features/visits/Review/ReviewList.tsx
  petclinic-frontend/src/features/visits/VisitListTable.tsx
  petclinic-frontend/src/features/visits/api/addVisit.ts
  petclinic-frontend/src/features/visits/api/exportVisitsCSV.ts
  petclinic-frontend/src/features/visits/api/getAllOwnerVisits.ts
  petclinic-frontend/src/features/visits/api/getAllVisits.ts
  petclinic-frontend/src/features/visits/api/getVisit.ts
  petclinic-frontend/src/features/visits/api/updateVisit.ts
  petclinic-frontend/src/features/visits/models/EditingVisit.tsx
  petclinic-frontend/src/features/visits/visits/VisitByVisitId.tsx
  visits-service-new/src/main/java/com/petclinic/visits/visitsservicenew/BusinessLayer/VisitServiceImpl.java
Labels: bug, VIST

#1088 feat(AUTH-CPC-852): allow users to only access dom based on role
  petclinic-frontend/src/features/bills/api/GetBillByBillId.tsx
  petclinic-frontend/src/features/bills/api/getAllBills.tsx
  petclinic-frontend/src/features/bills/api/getAllOverdueBills.tsx
  petclinic-frontend/src/features/bills/api/getAllPaidBills.tsx
  petclinic-frontend/src/features/bills/api/getAllUnpaidBills.tsx
  petclinic-frontend/src/features/bills/api/getBillByMonth.tsx
  petclinic-frontend/src/features/customers/api/getAllOwners.ts
  petclinic-frontend/src/features/customers/components/CustomerDetails.tsx
  petclinic-frontend/src/features/products/api/ProductDetails.tsx
  petclinic-frontend/src/features/products/api/getAllProducts.ts
  petclinic-frontend/src/features/products/api/getProductsByType.ts
  petclinic-frontend/src/features/products/api/getUserRatingsForProduct.ts
  petclinic-frontend/src/features/products/components/Product.tsx
  petclinic-frontend/src/features/veterinarians/VetListCards.tsx
  petclinic-frontend/src/features/veterinarians/api/getAllVets.ts
  petclinic-frontend/src/features/visits/CustomerVisitListTable.tsx
  petclinic-frontend/src/features/visits/Review/Api/getVisitByVisitId.ts
  petclinic-frontend/src/features/visits/VisitListTable.tsx
  petclinic-frontend/src/features/visits/api/getAllOwnerVisits.ts
  petclinic-frontend/src/features/visits/api/getAllVisits.ts
  petclinic-frontend/src/layouts/AppNavBar.tsx
  petclinic-frontend/src/pages/Customer/AllOwners.tsx
  petclinic-frontend/src/pages/Vet/Vet.tsx
  petclinic-frontend/src/pages/Vet/VetDetails.tsx
  petclinic-frontend/src/router.tsx
Labels: bug, AUTH

#1100 conf(AUTH-CPC-955): integrate JaCoCo code coverage in CI/CD pipeline
  .github/workflows/parallel_microservice_build.yml
  api-gateway/build.gradle
  petclinic-frontend/src/features/visits/VisitListTable.tsx
  petclinic-frontend/src/features/visits/api/getAllOwnerVisits.ts
  petclinic-frontend/src/features/visits/api/getAllVisits.ts
Labels: AUTH, CONF

#1102 feat(CUST-CPC-1499): Add pets by owners in profile page
  api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/CustomersServiceClient.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/BFFApiGatewayController.java
  api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/ApiGatewayControllerTest.java
  customers-service-reactive/src/main/java/com/petclinic/customersservice/business/DataSetupService.java
  customers-service-reactive/src/main/java/com/petclinic/customersservice/business/PetService.java
  customers-service-reactive/src/main/java/com/petclinic/customersservice/business/PetServiceImpl.java
  customers-service-reactive/src/main/java/com/petclinic/customersservice/presentationlayer/PetController.java
  customers-service-reactive/src/main/java/com/petclinic/customersservice/presentationlayer/PetRequestDTO.java
  customers-service-reactive/src/test/java/com/petclinic/customersservice/business/PetServiceUnitTest.java
  customers-service-reactive/src/test/java/com/petclinic/customersservice/presentationlayer/PetControllerUnitTest.java
  customers-service-reactive/src/test/java/com/petclinic/customersservice/presentationlayer/PetTypeControllerIntegrationTest.java
  petclinic-frontend/src/features/customers/api/addPetForOwner.ts
  petclinic-frontend/src/features/customers/api/getPetTypes.ts
  petclinic-frontend/src/features/customers/components/AddPetModal.css
  petclinic-frontend/src/features/customers/components/AddPetModal.tsx
  petclinic-frontend/src/features/customers/models/PetTypeModel.ts
  petclinic-frontend/src/features/customers/utils/petTypeMapping.ts
  petclinic-frontend/src/pages/Customer/ProfilePage.css
  petclinic-frontend/src/pages/Customer/ProfilePage.tsx
Labels: feat, CUST

#1105 feat(VIST-CPC-1520): update edit review permissions for admin
  api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/VisitController.java
  petclinic-frontend/src/features/visits/Review/ReviewList.tsx
  petclinic-frontend/src/features/visits/VisitListTable.tsx
Labels: VIST

#1079 bug(CART-CPC-1471): fix remove button functionality in wishlist
  api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/CartServiceClient.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v2/CartController.java
  cart-service/src/main/java/com/petclinic/cartsservice/businesslayer/CartService.java
  cart-service/src/main/java/com/petclinic/cartsservice/businesslayer/CartServiceImpl.java
  cart-service/src/main/java/com/petclinic/cartsservice/presentationlayer/CartController.java
  petclinic-frontend/src/features/carts/components/CartItem.tsx
  petclinic-frontend/src/features/carts/components/UserCart.tsx
Labels: bug, CART

#1111 bug(INVT-CPC-1465): Fix translation formatting
  petclinic-frontend/src/features/inventories/InventoryProducts.css
Labels: bug, INVT

#1078 bug(CART-CPC-1443): Fix improper use of API calls in FE
  package-lock.json
  petclinic-frontend/src/features/carts/api/addToCartFromProducts.ts
  petclinic-frontend/src/features/carts/api/addToWishlistFromProducts.ts
  petclinic-frontend/src/features/carts/api/getCart.ts
  petclinic-frontend/src/features/carts/api/getImage.ts
  petclinic-frontend/src/features/carts/components/CartTable.tsx
  petclinic-frontend/src/features/carts/components/UserCart.css
  petclinic-frontend/src/features/carts/components/UserCart.tsx
Labels: bug, CART

#1136 bug(CART-CPC-1469): hide wishlist button when out of stock
  petclinic-frontend/src/features/carts/components/CartItem.tsx
  petclinic-frontend/src/features/carts/components/UserCart.tsx
Labels: bug, CART

#1146 feat(CUST-CPC-666): update pet type
  api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v1/PetControllerV1.java
  api-gateway/src/main/resources/static/scripts/pet-type-list/pet-type-list.controller.js
  api-gateway/src/main/resources/static/scripts/pet-type-list/pet-type-list.template.html
  api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/V1/PetControllerV1Test.java
  customers-service-reactive/src/main/java/com/petclinic/customersservice/business/PetTypeServiceImpl.java
  customers-service-reactive/src/main/java/com/petclinic/customersservice/data/PetTypeRepo.java
  customers-service-reactive/src/test/java/com/petclinic/customersservice/presentationlayer/PetTypeControllerIntegrationTest.java
Labels: feat, CUST

#1142 feat(AUTH-CPC-1330): Re-design the React home page for users
  petclinic-frontend/src/features/faq/data/FaqItems.ts
  petclinic-frontend/src/features/faq/hooks/useFaqSearch.ts
  petclinic-frontend/src/features/faq/models/FaqItem.ts
  petclinic-frontend/src/features/home/components/Reveal.css
  petclinic-frontend/src/features/home/components/Reveal.tsx
  petclinic-frontend/src/features/home/components/ServiceCard.css
  petclinic-frontend/src/features/home/components/ServiceCard.tsx
  petclinic-frontend/src/features/home/components/VetCard.css
  petclinic-frontend/src/features/home/components/VetCard.tsx
  petclinic-frontend/src/features/home/hooks/useFeaturedVets.ts
  petclinic-frontend/src/layouts/AppFooter.css
  petclinic-frontend/src/layouts/AppFooter.tsx
  petclinic-frontend/src/pages/Contact/Contact.css
  petclinic-frontend/src/pages/Contact/Contact.tsx
  petclinic-frontend/src/pages/FAQ/FAQ.css
  petclinic-frontend/src/pages/FAQ/FAQ.tsx
  petclinic-frontend/src/pages/Home/Home.css
  petclinic-frontend/src/pages/Home/Home.tsx
  petclinic-frontend/src/pages/PrivacyPolicy/PrivacyPolicy.css
  petclinic-frontend/src/pages/PrivacyPolicy/PrivacyPolicy.tsx
  petclinic-frontend/src/router.tsx
  petclinic-frontend/src/shared/models/path.routes.ts
Labels: AUTH

#1159 Fix footer field misalignment and replace emojis
  petclinic-frontend/src/layouts/AppFooter.css
  petclinic-frontend/src/layouts/AppFooter.tsx
  petclinic-frontend/src/pages/Contact/Contact.css
  petclinic-frontend/src/pages/Contact/Contact.tsx
Labels: bug, AUTH

#1162 bug(AUTH-CPC-1598): Homepage contact band buttons are misplaced
  petclinic-frontend/src/pages/FAQ/FAQ.tsx
  petclinic-frontend/src/pages/Home/Home.tsx
Labels: AUTH

#1166 docs(AUTH-CPC-1577): Add Code Coverage Reports Access Documentation
  .github/workflows/parallel_microservice_build.yml
  README.md
  api-gateway/build.gradle
  docs/code-coverage-reports.md
Labels: documentation, AUTH

#1173 bug(VETS-CPC-1018): Use DTO for vet photos instead of Resource
  api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClient.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/Vets/PhotoRequestDTO.java
  api-gateway/src/test/java/com/petclinic/bffapigateway/domainclientlayer/VetsServiceClientIntegrationTest.java
  api-gateway/src/test/java/com/petclinic/bffapigateway/presentationlayer/v2/mockservers/MockServerConfigVetService.java
  petclinic-frontend/src/features/visits/VisitListTable.css
  vet-service/src/main/java/com/petclinic/vet/presentationlayer/PhotoRequestDTO.java
  vet-service/src/main/java/com/petclinic/vet/presentationlayer/VetController.java
  vet-service/src/main/java/com/petclinic/vet/servicelayer/PhotoService.java
  vet-service/src/main/java/com/petclinic/vet/servicelayer/PhotoServiceImpl.java
  vet-service/src/test/java/com/petclinic/vet/presentationlayer/VetControllerUnitTest.java
  vet-service/src/test/java/com/petclinic/vet/servicelayer/PhotoServiceImplTest.java
Labels: bug, VETS

#1107 feat(CUST-CPC-1537): Setup File Service
  api-gateway/src/main/java/com/petclinic/bffapigateway/domainclientlayer/FilesServiceClient.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/dtos/files/FileResponseDTO.java
  api-gateway/src/main/java/com/petclinic/bffapigateway/presentationlayer/v1/FileControllerV1.java
  api-gateway/src/main/resources/application.yml
  docker-compose.prod.yml
  docker-compose.yml
  docker-compose_no_FE.yml
  docs/diagrams/C4/champlain-pet-clinic-ms_C4_L2_container_diagram.puml
  files-service/Dockerfile
  files-service/files/businesslayer/file_service.go
  files-service/files/businesslayer/file_service_impl.go
  files-service/files/businesslayer/file_service_unit_test.go
  files-service/files/clientlayer/minio_service_client.go
  files-service/files/datalayer/buckets.go
  files-service/files/datalayer/file_info.go
  files-service/files/datalayer/file_info_repository.go
  files-service/files/datalayer/file_info_repository_intergration_test.go
  files-service/files/models/file_request_model.go
  files-service/files/models/file_response_model.go
  files-service/files/presentationlayer/file_controller.go
  files-service/files/presentationlayer/file_controller_integration_test.go
  files-service/files/presentationlayer/file_controller_unit_test.go
  files-service/files/presentationlayer/middleware.go
  files-service/files/util/data_loader.go
  files-service/files/util/exception/invalid_file_id_exception.go
  files-service/files/util/exception/not_found_exception.go
  files-service/files/util/global_exception_handler.go
  files-service/go.mod
  files-service/go.sum
  files-service/main.go
Labels: feat, CUST
